

networks:
  app-network:
    name: health-dashboard-network
    driver: bridge

services:
  frontend-dev:
    image: node:20-slim
    working_dir: /app
    volumes:
      - ./health-dashboard/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "9230:9229"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CI=true
      - REACT_APP_API_URL=http://west-us:8080
    command: >
      sh -c "npm install http-proxy-middleware --save-dev &&
             FORCE_COLOR=true npm run start:debug | cat"
    stdin_open: true
    tty: true
    depends_on:
      - west-us
      - central-us
    networks:
      - app-network

  west-us:
    build:
      context: .
      dockerfile: debug/Dockerfile.backend.debug
    security_opt: ["seccomp=unconfined"]
    cap_add: ["SYS_PTRACE"]
    ports:
      - "8081:8080"
      - "2345:2345"
    volumes:
      - ./health-dashboard/backend:/app/backend
    environment:
      - REGION=westus
      - VNET=10.1.0.0/16
      - DEBUG=true
      - PORT=8080
      - SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000
      - RESOURCE_GROUP=rg-dev-azure
      - APP_NAME=app-app-healthapp-westus-dev-31bb0r64
      - TM_PROFILE_NAME=tm-tm-healthapp-dev-jdm9m5hr
      - TENANT_ID=00000000-0000-0000-0000-000000000000
      - ROLE=primary
      - PAIRED_APP_NAME=app-app-healthapp-centralus-dev-i5sugn88
      - PAIRED_REGION=centralus
      - HOSTNAME=webapp-west-1
      - LOCAL_MODE=true
    networks:
      - app-network
      
  central-us:
    build:
      context: .
      dockerfile: debug/Dockerfile.backend.debug
    security_opt: ["seccomp=unconfined"]
    cap_add: ["SYS_PTRACE"]
    ports:
      - "8082:8080"
      - "2346:2345"
    volumes:
      - ./health-dashboard/backend:/app/backend
    environment:
      - REGION=centralus
      - VNET=10.2.0.0/16
      - DEBUG=true
      - PORT=8080
      - SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000
      - RESOURCE_GROUP=rg-dev-azure
      - APP_NAME=app-app-healthapp-centralus-dev-i5sugn88
      - TM_PROFILE_NAME=tm-tm-healthapp-dev-jdm9m5hr
      - TENANT_ID=00000000-0000-0000-0000-000000000000
      - ROLE=secondary
      - PAIRED_APP_NAME=app-app-healthapp-westus-dev-31bb0r64
      - PAIRED_REGION=westus
      - HOSTNAME=webapp-central-1
      - LOCAL_MODE=true
    networks:
      - app-network

  traffic-manager:
    build:
      context: .
      dockerfile: debug/Dockerfile.debug
    ports:
      - "8080:8080"
    environment:
      - PRIMARY_ENDPOINT=app-app-healthapp-westus
      - SECONDARY_ENDPOINT=app-app-healthapp-centralus
      - TM_PROFILE=healthapp-dev-20241331-jdm9m5hr.trafficmanager.net
    depends_on:
      - west-us
      - central-us
    networks:
      - app-network