services:
  frontend-dev:
    image: node:20-slim
    working_dir: /app
    volumes:
      - ./health-dashboard/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "9230:9229" # Map container's 9229 to host's 9230
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CI=true
    command: sh -c "npm install && npm run start:debug"
    stdin_open: true
    tty: true
    depends_on:
      - west-us
      - central-us

  west-us:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REGION=westus
      - VNET=10.1.0.0/16
      - DEBUG=true
      # Azure credentials and config
      - SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000
      - RESOURCE_GROUP=rg-dev-azure
      - APP_NAME=app-app-healthapp-westus-dev-31bb0r64
      - TM_PROFILE_NAME=tm-tm-healthapp-dev-jdm9m5hr
      - TENANT_ID=00000000-0000-0000-0000-000000000000
      - ROLE=primary
      - PAIRED_APP_NAME=app-app-healthapp-centralus-dev-i5sugn88
      - PAIRED_REGION=centralus
      - HOSTNAME=webapp-west-1
      - LOCAL_MODE=true
    ports:
      - "8081:8080"
    volumes:
      - ./health-dashboard/backend:/app/backend:ro
      - ./health-dashboard/frontend/src:/app/frontend/src:ro

  central-us:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REGION=centralus
      - VNET=10.2.0.0/16
      - DEBUG=true
      # Azure credentials and config
      - SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000
      - RESOURCE_GROUP=rg-dev-azure
      - APP_NAME=app-app-healthapp-centralus-dev-i5sugn88
      - TM_PROFILE_NAME=tm-tm-healthapp-dev-jdm9m5hr
      - TENANT_ID=00000000-0000-0000-0000-000000000000
      - ROLE=secondary
      - PAIRED_APP_NAME=app-app-healthapp-westus-dev-31bb0r64
      - PAIRED_REGION=westus
      - HOSTNAME=webapp-central-1
      - LOCAL_MODE=true
    ports:
      - "8082:8080"
    volumes:
      - ./health-dashboard/backend:/app/backend:ro
      - ./health-dashboard/frontend/src:/app/frontend/src:ro

  traffic-manager:
    build:
      context: .
      dockerfile: debug/Dockerfile.debug
    ports:
      - "8080:8080"
    environment:
      - PRIMARY_ENDPOINT=app-app-healthapp-westus
      - SECONDARY_ENDPOINT=app-app-healthapp-centralus
      - TM_PROFILE=healthapp-dev-20241331-jdm9m5hr.trafficmanager.net
    depends_on:
      - west-us
      - central-us