name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME_PRIMARY: app-app-healthapp-westus-dev-31bb0r64
  AZURE_WEBAPP_NAME_SECONDARY: app-app-healthapp-centralus-dev-i5sugn88
  PRIMARY_REGION: "westus"
  SECONDARY_REGION: "centralus"
  PRIMARY_ROLE: "primary"
  SECONDARY_ROLE: "secondary"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Extract Subscription ID
      run: |
        SUBSCRIPTION_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .subscriptionId)
        echo "SUBSCRIPTION_ID=$SUBSCRIPTION_ID" >> $GITHUB_ENV

    - name: Build Frontend
      working-directory: ./health-dashboard/frontend
      run: |
        npm install
        CI=false npm run build

    - name: Build Backend
      working-directory: ./health-dashboard/backend
      env:
        RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        TM_PROFILE_NAME: ${{ secrets.AZURE_TM_PROFILE_NAME }}
      run: |
        go mod download
        go build -v ./...
        go test ./...

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_REGISTRY_NAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and Push Docker Image
      working-directory: ./health-dashboard
      run: |
        docker build -t ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/healthapp:${{ github.sha }} .
        docker push ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/healthapp:${{ github.sha }}

    - name: Deploy to Primary Region
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_PRIMARY }}
        images: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/healthapp:${{ github.sha }}
      env:
        RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        TM_PROFILE_NAME: ${{ secrets.AZURE_TM_PROFILE_NAME }}
        REGION: ${{ env.PRIMARY_REGION }}
        ROLE: ${{ env.PRIMARY_ROLE }}

    - name: Deploy to Secondary Region
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_SECONDARY }}
        images: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/healthapp:${{ github.sha }}
      env:
        RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        TM_PROFILE_NAME: ${{ secrets.AZURE_TM_PROFILE_NAME }}
        REGION: ${{ env.SECONDARY_REGION }}
        ROLE: ${{ env.SECONDARY_ROLE }}